### ISSUE TITLE
Instructions unclear - Section 7

### ISSUE THREAD

**Issue by liamrahav** [MakeSchool-Tutorials/Flappy-Bird-SpriteBuilder-Swift#11]
The code block:

```
spawnNewObstacle()
spawnNewObstacle()
spawnNewObstacle()
```

Is implied to be a testing piece of code. This is not the case as this code block is necessary for the Flappy Bird game to work properly. Rewording of the instructions is necessary to make the need for these lines more clear. It also might be a good idea to make it into a for loop as follows:

```
for i in 0...2 {
    spawnNewObstacle()
}
```

This loop makes the code seem more "official" and less like a piece of testing/debugging code.

**Comment by dionlarson** [comment]
Fixed in 5e197333aebffa6f85d5d6f93802409af8941996
