### ISSUE TITLE
TouchesBegan

### ISSUE THREAD

**Issue by ozzymanfest08** [MakeSchool-Tutorials/Flappy-Bird-SpriteBuilder-Swift#13]
Having Issues with making the bunny hop when you touch the screen. The code provided is dated, and when I change to the up to date function names nothing happens

**Comment by ozzymanfest08** [comment]
more specifically I receive this error for the method:
 override func touchBegan(_ touch: CCTouch!, with event: CCTouchEvent!)
    {
        hero.physicsBody.applyImpulse(ccp(0, 300))
    }
 thread 1: EXC_BAD_INSTRUCTION (code= EXC_1386_INVOP, subcode = 0x0)

**Comment by soggybag** [comment]
This tutorial has been updated for SpriteKit and Swift. I would recommend building this project. It might be easier, and will be more update to date. 

Here is a link to the updated tutorial: 
https://github.com/soggybag/Hoppy-Bunny-SpriteKit-Swift

Here are some videos to help you get started: 
https://www.youtube.com/watch?v=Jy9fWSEwMkU&list=PLoN_ejT35AEgjb1Th-EUDG83bA179Ks2S&index=1
