### ISSUE TITLE
High level comments

### ISSUE THREAD

**Issue by JorrieB** [MakeSchool-Tutorials/Flappy-Bird-SpriteBuilder-Swift#4]
#1 In changing the code to conform to the swift style guide, we will introduce the 'weak' keyword. The tutorial has no mention of what this keyword means, so that may need to be updated.

**Comment by JorrieB** [comment]
#2 We use type inference in some places and explicit type declaration in others. This is necessary as we must explicitly declare CGFloat for interaction with some Objective-C classes, but it may need to be touched upon.

**Comment by JorrieB** [comment]
#3 On the other hand, I really like the level of detail the tutorial goes into in its current state; it's not terribly overwhelming and in an hour or two, the student can go from zero to flapping flies. Glossing over the details I posted above might definitely be worth it as they'll probably mean nothing to beginners.

**Comment by dionlarson** [comment]
Reformatted tutorial.
