### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by orcudy** [MakeSchool-Tutorials/Flappy-Bird-SpriteBuilder-Swift#5]
1. Explanation of position vs anchor and correlation of the two seems necessary (including the convention of 0,0 being top left corner of device)
2. Magic numbers are confusing -- why did we choose position (0, 12) for the ground image? Seems like explanation is needed.
3. When instructed to set specific attributes in SpriteBuilder, distinguish SpriteBuilder specific terms by setting bold or italicizing. i.e. position => _Position_ 
4. When creating hero, specifically when creating new CCB-file, note that you must DOUBLE click the new file in the Node Tree to get access to its attributes
5. The following caution statement is unnecessary and confusing:  
   "The original Objective-C Flappy Fly tutorial had you enable physics on the Fly that was added to the Stage, not the Fly in the Hero.ccb. This was only possible due to a SpriteBuilder bug since you should never be allowed to enable physics on a Sub File (CCBFile) node. Instead you must enable physics on the node referenced by the Sub File node as you've done here.”
6. It should be noted that you have to publish all .ccb files before you will be able to see them when added to the main scene (i.e. I dragged Hero.ccb to MainScene.ccb and didn’t see the fly until I actually published)
7. Doc root var screenshots should match instruction in tutorial (currently, screenshots do not match)
8. When instructing to write code, include previously written code to give students a better idea of where the code should go
9. when initializing the grounds variable, why are we using this: 

``` swift
var grounds : [CCSprite] = []
```

I think this is clearer (and the way Apple shows in its docs):

``` swift
var grounds = [CCSprite]()
```

**Comment by orcudy** [comment]
Collision handler for _level_ and _hero_ collisions must be inserted into the MainScene class declaration. It cannot be inserted **anywhere** in the MainScene.swift file, as stated in the tutorial

**Comment by orcudy** [comment]
"Lastly, open Hero.ccb and select the CCSprite root node. Check the Enable Physics checkbox, set the body type to Dynamic and enter hero in the Collision Type field. Also uncheck both Affected by Gravity and Allows Rotation checkboxes." 

Why are we instructing to **uncheck** gravity and rotation? This breaks the game for me -- when impulse is applied, flappy just soars upwards indefinitely.

**Comment by orcudy** [comment]
Should be noted that the restart button should be placed outside of the physics node.

**Comment by orcudy** [comment]
In ccPhysicsCollisionBegin():

remove “restart.visible = true”

**Comment by dionlarson** [comment]
Reformatted tutorial.
